project:
  type: website
  output-dir: docs
website:
  title: "Tianxu Jia's Breaking the AI Code"
  navbar:
    right:
      - about.qmd
      - AI-world.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



